### ISSUE TITLE
Add upc to beverages and add beverage_details model

### ISSUE THREAD

**Issue by mascott** [mascott/beers#1]
I'm thinking beverages are going to be broken into two pieces. The current beverage model is going to have it's name field replaced with a `upc` field and it will have a beverage_details record. The beverage details will hold all of the data like name, ABW, IBU, etc.

**Comment by amar47shah** [comment]
@mascott interesting idea, but I'm not really seeing the reasoning behind this.

A separate model would be good if more than one beverage can share the same details, but since `name` will be in the details, that seems very unlikely. While I could see some details being repeated together from beverage to beverage, I wouldn't want to strap us in to this design at this early stage.

Let me know what you think. Propose closing this for now.

**Comment by mascott** [comment]
Hah. I'm going to pretend like this one never existed.
